# fly.toml app configuration file generated for constelaciones-backend-fly on 2023-06-09T11:56:17-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "constelaciones-backend-fly"
primary_region = "eze"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
